<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Findirector.Domain/Findirector.Domain.csproj" />
    <ProjectReference Include="../Findirector.Application/Findirector.Application.csproj" />
    <ProjectReference Include="../Findirector.Infrastructure/Findirector.Infrastructure.csproj" />
  </ItemGroup>
</Project>
